alias lla="ls -lha"    # shorthand full ls
alias ports="netstat -tulpn"    # show active ports
alias syscenable="systemctl enable"    # enable systemd service
alias syscdisable="systemctl disable"    # disable systemd service
alias syscrestart="systemctl restart"    # restart systemd service
alias syscreload="systemctl reload"    # reload systemd service
alias syscstop="systemctl stop"    # stop systemd service
alias syscstart="systemctl start"    # start systemd service
alias aptin="apt install -y"    # shorthand apt install
alias aptup="apt update"
alias pgrep="ps -ef | grep"    # grep for processes
alias portgrep="netstat -tulpn | grep"    # grep for ports
alias cd..="cd .."    # one dir up, windows style
alias ..="cd .."    # one dir up, shorthand
alias cls="clear"    # clear, windpws style
alias findhere="find . -name"    # fimd shorthand
alias diskfree="df -Tha --total"    # disk space shorthand
alias dirfree="du -ach | sort -h"    # directory space shorthand
alias mkdir="mkdir -pv"    # better mkdir
alias histgrep="history | grep"    # grep your bash history
alias mountgrep="mount | grep"
alias rebash="source ~/.bashrc"
alias mkcd='mkcd_func(){ mkdir -p "$1" && cd "$1"; unset -f mkcd_func; }; mkcd_func'
